# Generated by Django 5.2.5 on 2025-09-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("altars", "0006_alter_contact_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("D", "Donations"), ("G", "General")],
                max_length=50,
                null=True,
            ),
        ),
    ]
