# Generated by Django 5.2.7 on 2025-11-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("altars", "0009_alter_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="altar",
            name="address1",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="altar",
            name="address2",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="altar",
            name="address3",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="altar",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="altar",
            name="location",
            field=models.CharField(blank=True, default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="altar",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="altar",
            name="zipcode",
            field=models.CharField(blank=True, default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("D", "Donations"), ("G", "General")],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="website",
            field=models.URLField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("V", "Viewing"),
                    ("M", "Mass"),
                    ("F", "Meals"),
                    ("B", "Blessing"),
                    ("T", "Tupa Tupa"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
